const en = [
  {
    code: 'Backquote',
    key: '`',
    keyCaps: '`',
    keyUpperCase: '~',
  },
  {
    code: 'Digit1',
    key: '1',
    keyCaps: '1',
    keyUpperCase: '!',
  },
  {
    code: 'Digit2',
    key: '2',
    keyCaps: '2',
    keyUpperCase: '@',
  },
  {
    code: 'Digit3',
    key: '3',
    keyCaps: '3',
    keyUpperCase: '#',
  },
  {
    code: 'Digit4',
    key: '4',
    keyCaps: '4',
    keyUpperCase: '$',
  },
  {
    code: 'Digit5',
    key: '5',
    keyCaps: '5',
    keyUpperCase: '%',
  },
  {
    code: 'Digit6',
    key: '6',
    keyCaps: '6',
    keyUpperCase: '^',
  },
  {
    code: 'Digit7',
    key: '7',
    keyCaps: '7',
    keyUpperCase: '&',
  },
  {
    code: 'Digit8',
    key: '8',
    keyCaps: '8',
    keyUpperCase: '*',
  },
  {
    code: 'Digit9',
    key: '9',
    keyCaps: '9',
    keyUpperCase: '(',
  },
  {
    code: 'Digit0',
    key: '0',
    keyCaps: '0',
    keyUpperCase: ')',
  },
  {
    code: 'Minus',
    key: '-',
    keyCaps: '-',
    keyUpperCase: '_',
  },
  {
    code: 'Equal',
    key: '=',
    keyCaps: '=',
    keyUpperCase: '+',
  },
  {
    code: 'Backspace',
    key: 'backspace',
    keyCaps: 'backspace',
    keyUpperCase: 'backspace',
  },
  {
    code: 'Tab',
    key: 'tab',
    keyCaps: 'tab',
    keyUpperCase: 'tab',
  },
  {
    code: 'KeyQ',
    key: 'q',
    keyCaps: 'Q',
    keyUpperCase: 'Q',
  },
  {
    code: 'KeyW',
    key: 'w',
    keyCaps: 'W',
    keyUpperCase: 'W',
  },
  {
    code: 'KeyE',
    key: 'e',
    keyCaps: 'E',
    keyUpperCase: 'E',
  },
  {
    code: 'KeyR',
    key: 'r',
    keyCaps: 'R',
    keyUpperCase: 'R',
  },
  {
    code: 'KeyT',
    key: 't',
    keyCaps: 'T',
    keyUpperCase: 'T',
  },
  {
    code: 'KeyY',
    key: 'y',
    keyCaps: 'Y',
    keyUpperCase: 'Y',
  },
  {
    code: 'KeyU',
    key: 'u',
    keyCaps: 'U',
    keyUpperCase: 'U',
  },
  {
    code: 'KeyI',
    key: 'i',
    keyCaps: 'I',
    keyUpperCase: 'I',
  },
  {
    code: 'KeyO',
    key: 'o',
    keyCaps: 'O',
    keyUpperCase: 'O',
  },
  {
    code: 'KeyP',
    key: 'p',
    keyCaps: 'P',
    keyUpperCase: 'P',
  },
  {
    code: 'BracketLeft',
    key: '[',
    keyCaps: '[',
    keyUpperCase: '{',
  },
  {
    code: 'BracketRight',
    key: ']',
    keyCaps: ']',
    keyUpperCase: '}',
  },
  {
    code: 'Delete',
    key: 'delete',
    keyCaps: 'delete',
    keyUpperCase: 'delete',
  },
  {
    code: 'CapsLock',
    key: 'capsLock',
    keyCaps: 'capsLock',
    keyUpperCase: 'capsLock',
  },
  {
    code: 'KeyA',
    key: 'a',
    keyCaps: 'A',
    keyUpperCase: 'A',
  },
  {
    code: 'KeyS',
    key: 's',
    keyCaps: 'S',
    keyUpperCase: 'S',
  },
  {
    code: 'KeyD',
    key: 'd',
    keyCaps: 'D',
    keyUpperCase: 'D',
  },
  {
    code: 'KeyF',
    key: 'f',
    keyCaps: 'F',
    keyUpperCase: 'F',
  },
  {
    code: 'KeyG',
    key: 'g',
    keyCaps: 'G',
    keyUpperCase: 'G',
  },
  {
    code: 'KeyH',
    key: 'h',
    keyCaps: 'H',
    keyUpperCase: 'H',
  },
  {
    code: 'KeyJ',
    key: 'j',
    keyCaps: 'J',
    keyUpperCase: 'J',
  },
  {
    code: 'KeyK',
    key: 'k',
    keyCaps: 'K',
    keyUpperCase: 'K',
  },
  {
    code: 'KeyL',
    key: 'l',
    keyCaps: 'L',
    keyUpperCase: 'L',
  },
  {
    code: 'Semicolon',
    key: ';',
    keyCaps: ';',
    keyUpperCase: ':',
  },
  {
    code: 'Quote',
    key: "'",
    keyCaps: "'",
    keyUpperCase: '"',
  },
  {
    code: 'Enter',
    key: 'enter',
    keyCaps: 'enter',
    keyUpperCase: 'enter',
  },
  {
    code: 'ShiftLeft',
    key: 'shiftL',
    keyCaps: 'shiftL',
    keyUpperCase: 'shiftL',
  },
  {
    code: 'KeyZ',
    key: 'z',
    keyCaps: 'Z',
    keyUpperCase: 'Z',
  },
  {
    code: 'KeyX',
    key: 'x',
    keyCaps: 'X',
    keyUpperCase: 'X',
  },
  {
    code: 'KeyC',
    key: 'c',
    keyCaps: 'C',
    keyUpperCase: 'C',
  },
  {
    code: 'KeyV',
    key: 'v',
    keyCaps: 'V',
    keyUpperCase: 'V',
  },
  {
    code: 'KeyB',
    key: 'b',
    keyCaps: 'B',
    keyUpperCase: 'B',
  },
  {
    code: 'KeyN',
    key: 'n',
    keyCaps: 'N',
    keyUpperCase: 'N',
  },
  {
    code: 'KeyM',
    key: 'm',
    keyCaps: 'M',
    keyUpperCase: 'M',
  },
  {
    code: 'Comma',
    key: ',',
    keyCaps: ',',
    keyUpperCase: '<',
  },
  {
    code: 'Period',
    key: '.',
    keyCaps: '.',
    keyUpperCase: '>',
  },
  {
    code: 'Slash',
    key: '/',
    keyCaps: '/',
    keyUpperCase: '?',
  },
  {
    code: 'Backslash',
    key: '\\',
    keyCaps: '\\',
    keyUpperCase: '|',
  },
  {
    code: 'ArrowUp',
    key: '\u25B2',
    keyCaps: '\u25B2',
    keyUpperCase: '\u25B2',
  },
  {
    code: 'ShiftRight',
    key: 'shiftR',
    keyCaps: 'shiftR',
    keyUpperCase: 'shiftR',
  },

  {
    code: 'ControlLeft',
    key: 'control',
    keyCaps: 'control',
    keyUpperCase: 'control',
  },
  {
    code: 'MetaLeft',
    key: 'meta',
    keyCaps: 'meta',
    keyUpperCase: 'meta',
  },
  {
    code: 'AltLeft',
    key: 'altL',
    keyCaps: 'altL',
    keyUpperCase: 'altL',
  },
  {
    code: 'Space',
    key: ' ',
    keyCaps: ' ',
    keyUpperCase: ' ',
  },
  {
    code: 'AltRight',
    key: 'altR',
    keyCaps: 'altR',
    keyUpperCase: 'altR',
  },
  {
    code: 'ControlRight',
    key: 'control',
    keyCaps: 'control',
    keyUpperCase: 'control',
  },
  {
    code: 'ArrowLeft',
    key: '\u25C4',
    keyCaps: '\u25C4',
    keyUpperCase: '\u25C4',
  },
  {
    code: 'ArrowDown',
    key: '\u25BC',
    keyCaps: '\u25BC',
    keyUpperCase: '\u25BC',
  },
  {
    code: 'ArrowRight',
    key: '\u25BA',
    keyCaps: '\u25BA',
    keyUpperCase: '\u25BA',
  },
];

export { en };
