const ru = [
  {
    code: 'Backquote',
    key: 'ё',
    keyCaps: 'Ё',
    keyUpperCase: 'Ё',
  },
  {
    code: 'Digit1',
    key: '1',
    keyCaps: '1',
    keyUpperCase: '!',
  },
  {
    code: 'Digit2',
    key: '2',
    keyCaps: '2',
    keyUpperCase: '"',
  },
  {
    code: 'Digit3',
    key: '3',
    keyCaps: '3',
    keyUpperCase: '№',
  },
  {
    code: 'Digit4',
    key: '4',
    keyCaps: '4',
    keyUpperCase: ';',
  },
  {
    code: 'Digit5',
    key: '5',
    keyCaps: '5',
    keyUpperCase: '%',
  },
  {
    code: 'Digit6',
    key: '6',
    keyCaps: '6',
    keyUpperCase: ':',
  },
  {
    code: 'Digit7',
    key: '7',
    keyCaps: '7',
    keyUpperCase: '?',
  },
  {
    code: 'Digit8',
    key: '8',
    keyCaps: '8',
    keyUpperCase: '*',
  },
  {
    code: 'Digit9',
    key: '9',
    keyCaps: '9',
    keyUpperCase: '(',
  },
  {
    code: 'Digit0',
    key: '0',
    keyCaps: '0',
    keyUpperCase: ')',
  },
  {
    code: 'Minus',
    key: '-',
    keyCaps: '-',
    keyUpperCase: '_',
  },
  {
    code: 'Equal',
    key: '=',
    keyCaps: '=',
    keyUpperCase: '+',
  },
  {
    code: 'Backspace',
    key: 'backspace',
    keyCaps: 'backspace',
    keyUpperCase: 'backspace',
  },
  {
    code: 'Tab',
    key: 'tab',
    keyCaps: 'tab',
    keyUpperCase: 'tab',
  },
  {
    code: 'KeyQ',
    key: 'й',
    keyCaps: 'Й',
    keyUpperCase: 'Й',
  },
  {
    code: 'KeyW',
    key: 'ц',
    keyCaps: 'Ц',
    keyUpperCase: 'Ц',
  },
  {
    code: 'KeyE',
    key: 'у',
    keyCaps: 'У',
    keyUpperCase: 'У',
  },
  {
    code: 'KeyR',
    key: 'к',
    keyCaps: 'К',
    keyUpperCase: 'К',
  },
  {
    code: 'KeyT',
    key: 'е',
    keyCaps: 'Е',
    keyUpperCase: 'Е',
  },
  {
    code: 'KeyY',
    key: 'н',
    keyCaps: 'Н',
    keyUpperCase: 'Н',
  },
  {
    code: 'KeyU',
    key: 'г',
    keyCaps: 'Г',
    keyUpperCase: 'Г',
  },
  {
    code: 'KeyI',
    key: 'ш',
    keyCaps: 'Ш',
    keyUpperCase: 'Ш',
  },
  {
    code: 'KeyO',
    key: 'щ',
    keyCaps: 'Щ',
    keyUpperCase: 'Щ',
  },
  {
    code: 'KeyP',
    key: 'з',
    keyCaps: 'З',
    keyUpperCase: 'З',
  },
  {
    code: 'BracketLeft',
    key: 'х',
    keyCaps: 'Х',
    keyUpperCase: 'Х',
  },
  {
    code: 'BracketRight',
    key: 'ъ',
    keyCaps: 'Ъ',
    keyUpperCase: 'Ъ',
  },
  {
    code: 'Delete',
    key: 'delete',
    keyCaps: 'delete',
    keyUpperCase: 'delete',
  },
  {
    code: 'CapsLock',
    key: 'capsLock',
    keyCaps: 'capsLock',
    keyUpperCase: 'capsLock',
  },
  {
    code: 'KeyA',
    key: 'ф',
    keyCaps: 'Ф',
    keyUpperCase: 'Ф',
  },
  {
    code: 'KeyS',
    key: 'ы',
    keyCaps: 'Ы',
    keyUpperCase: 'Ы',
  },
  {
    code: 'KeyD',
    key: 'в',
    keyCaps: 'В',
    keyUpperCase: 'В',
  },
  {
    code: 'KeyF',
    key: 'а',
    keyCaps: 'А',
    keyUpperCase: 'А',
  },
  {
    code: 'KeyG',
    key: 'п',
    keyCaps: 'П',
    keyUpperCase: 'П',
  },
  {
    code: 'KeyH',
    key: 'р',
    keyCaps: 'Р',
    keyUpperCase: 'Р',
  },
  {
    code: 'KeyJ',
    key: 'о',
    keyCaps: 'О',
    keyUpperCase: 'О',
  },
  {
    code: 'KeyK',
    key: 'л',
    keyCaps: 'Л',
    keyUpperCase: 'Л',
  },
  {
    code: 'KeyL',
    key: 'д',
    keyCaps: 'Д',
    keyUpperCase: 'Д',
  },
  {
    code: 'Semicolon',
    key: 'ж',
    keyCaps: 'Ж',
    keyUpperCase: 'Ж',
  },
  {
    code: 'Quote',
    key: 'э',
    keyCaps: 'Э',
    keyUpperCase: 'Э',
  },
  {
    code: 'Enter',
    key: 'enter',
    keyCaps: 'enter',
    keyUpperCase: 'enter',
  },
  {
    code: 'ShiftLeft',
    key: 'shiftL',
    keyCaps: 'shiftL',
    keyUpperCase: 'shiftL',
  },
  {
    code: 'KeyZ',
    key: 'я',
    keyCaps: 'Я',
    keyUpperCase: 'Я',
  },
  {
    code: 'KeyX',
    key: 'ч',
    keyCaps: 'Ч',
    keyUpperCase: 'Ч',
  },
  {
    code: 'KeyC',
    key: 'с',
    keyCaps: 'С',
    keyUpperCase: 'С',
  },
  {
    code: 'KeyV',
    key: 'м',
    keyCaps: 'М',
    keyUpperCase: 'М',
  },
  {
    code: 'KeyB',
    key: 'и',
    keyCaps: 'И',
    keyUpperCase: 'И',
  },
  {
    code: 'KeyN',
    key: 'т',
    keyCaps: 'Т',
    keyUpperCase: 'Т',
  },
  {
    code: 'KeyM',
    key: 'ь',
    keyCaps: 'Ь',
    keyUpperCase: 'Ь',
  },
  {
    code: 'Comma',
    key: 'б',
    keyCaps: 'Б',
    keyUpperCase: 'Б',
  },
  {
    code: 'Period',
    key: 'ю',
    keyCaps: 'Ю',
    keyUpperCase: 'Ю',
  },
  {
    code: 'Slash',
    key: '.',
    keyCaps: '.',
    keyUpperCase: ',',
  },
  {
    code: 'Backslash',
    key: '\\',
    keyCaps: '\\',
    keyUpperCase: '/',
  },
  {
    code: 'ArrowUp',
    key: '\u25B2',
    keyCaps: '\u25B2',
    keyUpperCase: '\u25B2',
  },
  {
    code: 'ShiftRight',
    key: 'shiftR',
    keyCaps: 'shiftR',
    keyUpperCase: 'shiftR',
  },

  {
    code: 'ControlLeft',
    key: 'control',
    keyCaps: 'control',
    keyUpperCase: 'control',
  },
  {
    code: 'MetaLeft',
    key: 'meta',
    keyCaps: 'meta',
    keyUpperCase: 'meta',
  },
  {
    code: 'AltLeft',
    key: 'altL',
    keyCaps: 'altL',
    keyUpperCase: 'altL',
  },
  {
    code: 'Space',
    key: ' ',
    keyCaps: ' ',
    keyUpperCase: ' ',
  },
  {
    code: 'AltRight',
    key: 'altR',
    keyCaps: 'altR',
    keyUpperCase: 'altR',
  },
  {
    code: 'ControlRight',
    key: 'control',
    keyCaps: 'control',
    keyUpperCase: 'control',
  },
  {
    code: 'ArrowLeft',
    key: '\u25C4',
    keyCaps: '\u25C4',
    keyUpperCase: '\u25C4',
  },
  {
    code: 'ArrowDown',
    key: '\u25BC',
    keyCaps: '\u25BC',
    keyUpperCase: '\u25BC',
  },
  {
    code: 'ArrowRight',
    key: '\u25BA',
    keyCaps: '\u25BA',
    keyUpperCase: '\u25BA',
  },
];

export default ru;
